name: Update changelog

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  update-changelog:
    uses: jtl-software/changelog-extractor/.github/workflows/update-changelog.yaml@21926464ffba4e610cd0e2c0f9d277d3ffe8ca56 # v2
    with:
      system-name: ${{ vars.CHANGELOG_SYSTEM_NAME }}
      changelog-file: CHANGELOG.md
      app-id: ${{ vars.GH_APP_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
