name: Update changelog

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  update-changelog:
    uses: jtl-software/changelog-extractor/.github/workflows/update-changelog.yaml@CO-3490-changelog-extractor-not-working # v2
    with:
      system-name: ${{ vars.CHANGELOG_SYSTEM_NAME }}
      changelog-file: CHANGELOG.md
      jira-release-prefix: Core
      app-id: ${{ vars.GH_APP_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      ATLASSIAN_EMAIL: ${{ secrets.ATLASSIAN_EMAIL }}
      ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
